spring.application.name=testing

#docker
spring.docker.compose.file=backend/docker-compose.yml

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/testing_system
spring.datasource.username=admin
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=password

#test jwt token
jwt.secret=404e635266556a586e3272357538782f413f4428472b4b6250645367566b5970

