spring.application.name=testing

#docker
spring.docker.compose.file=backend/docker-compose.yml

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/testing_system
spring.datasource.username=admin
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.session.store-type=redis
server.servlet.session.timeout=30m

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=password

#spring security
spring.security.user.name=admin
spring.security.user.password=secret

#jpa
spring.jpa.open-in-view=false


